### ISSUE TITLE
Unable to create organization after registering user

### ISSUE THREAD

**Issue by rbenkal** [oneops/oneops-admin#74]
Hi,

I booted up a vagrant environment in my local and the VM started up. Since, the display didn't start I went ahead and started the display using /opt/oneops/start-display.sh to bring up rails.

Now I am able to hit http://localhost:9090 and register a user. However, I get an error when I am trying to create an organization. Below is the error I am getting.

What exactly I am missing. Is there a way to check if all the background processes were started successfully?

![image](https://cloud.githubusercontent.com/assets/7548497/16954773/c9d647a2-4def-11e6-8a10-f5966142eb5e.png)

**Comment by mosabua** [comment]
Closing this old issues. Please reopen with more details if you still experience this problem.
